name:                advent
version:             0.1.0.0
github:              tuxagon/advent-haskell
license:             BSD3

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/advent#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.9 && < 0.6
- text >= 1.2.2 && < 1.3
- bytestring >= 0.10.8 && < 0.11
- pureMD5 >= 2.1.3 && < 2.2

library:
  source-dirs: src

executables:
  advent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent

tests:
  advent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
